# Generated by Django 3.0.5 on 2020-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateyou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
